version: '3'

services:
    lumen:
        container_name: lumen
        user: "1000"
        ports:
            - "8000:8000"
        build: '.'
        command: php -S lumen:8000 -t public
        restart: always
        volumes:
            - .:/var/www/html
        networks:
            - framenet
    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysqldata:/var/lib/mysql/
        networks:
            - framenet
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - framenet

networks:
    framenet:
        driver: bridge
volumes:
    mysqldata:
        driver: local
